# eugenes_horse_whistle.toml
entitySearchRadius = 128.0
#遍历实体最大范围值，默认为在128格范围内寻找你的马
maxTeleportOffset = 32
#传送偏移值，默认为将马传送到你身边32格内的某个位置，如果改成1，马就会直接出现在你的身边
teleportDistanceThreshold = 64.0
#传送与寻路的界限，默认为如果主人与马的距离小于64，马将会走向主人
playWhistleSound = true
#是否播放马哨声音和动作
spurs = true
#是否启用马刺
